training: /home/mlx/ai-ml/zarrs/
validation: /home/mlx/ai-ml/panguweather-${data.resolution}
test: /home/mlx/ai-ml/panguweather-${data.resolution}
predict: /home/mlx/ai-ml/panguweather-${data.resolution}
output: ${oc.env:SCRATCH}/aifs/${data.resolution}
logs:
  wandb: ${hardware.paths.output}/logs/wandb
  tensorboard: ${hardware.paths.output}/logs/tensorboard
checkpoints: ${hardware.paths.output}/checkpoint
plots: ${hardware.paths.output}/plots
graph: /home/mlx/data/graphs/
