training: /lus/h2resw01/fws4/lb/project/ai-ml/zarrs/
validation: /lus/h2resw01/fws4/lb/project/ai-ml/panguweather-${data.resolution}
test: /lus/h2resw01/fws4/lb/project/ai-ml/panguweather-${data.resolution}
predict: /lus/h2resw01/fws4/lb/project/ai-ml/panguweather-${data.resolution}
output: ${oc.env:SCRATCH}/aifs/${data.resolution}/
logs: ${hardware.paths.output}/logs
checkpoints: ${hardware.paths.output}/checkpoint
plots: ${hardware.paths.output}/plots
graph: /home/mlx/data/graphs/
