training:
  an: /lus/h2resw01/fws4/lb/project/ai-ml/panguweather-${data.resolution}
  ens: /ec/res4/scratch/mafp/sandbox/ecflow-data/zarr/
validation:
  an: /lus/h2resw01/fws4/lb/project/ai-ml/panguweather-${data.resolution}
  ens: /ec/res4/scratch/mafp/sandbox/ecflow-data/zarr/
test: /lus/h2resw01/fws4/lb/project/ai-ml/panguweather-${data.resolution}
predict: /lus/h2resw01/fws4/lb/project/ai-ml/panguweather-${data.resolution}
output: ${oc.env:SCRATCH}/aifs/${data.resolution}
logs:
  wandb: ${hardware.paths.output}/logs/wandb
  tensorboard: ${hardware.paths.output}/logs/tensorboard
checkpoints: ${hardware.paths.output}/checkpoint
plots: ${hardware.paths.output}/plots
graph: /home/mlx/data/graphs/
