input:
  # zarr is also supported
  # the zarr data are under /ec/res4/scratch/syma/era5/o160/zarr/[pl | sfc]
  format: zarr
  resolution: o96
  training: 
    basedir: /lus/h2resw01/fws4/lb/project/ai-ml/zarrs/
    filename: aifs-era5-{resolution}-1979-2015-1h.zarr
  validation:
    basedir: /lus/h2resw01/fws4/lb/project/ai-ml/zarrs/
    filename: aifs-era5-{resolution}-2016-2017-1h.zarr
  test:
    basedir: /lus/h2resw01/fws4/lb/project/ai-ml/zarrs/
    filename: aifs-era5-{resolution}-2016-2017-1h.zarr
  predict:
    basedir: /lus/h2resw01/fws4/lb/project/ai-ml/zarrs/
    filename: aifs-era5-{resolution}-2016-2017-1h.zarr
  pl:
      names:
      # not used!
        - q
        - t
        - u
        - v
        - w
        - z
      levels:
        - 50
        - 100
        - 150
        - 200
        - 250
        - 300
        - 400
        - 500
        - 600
        - 700
        - 850
        - 925
        - 1000
  sfc:
      names:
      # not used!
        - msl
        - z
        - lsm
  # features that are not part of the forecast state
  # these are presumed to be located at the "end" of the flattened (bs, latlon, nvar) input tensor
  num-features: 98
  num-aux-features: 13  # all 2D fields
  loss-scaling-pl:
    - 0.6
    - 6
    - 0.8
    - 0.5
    - 0.02
    - 12
  loss-scaling-sfc:
    - 0.1
    - 1
    - 0.1
    - 0.1
    - 0.1
    - 1
    - 0.1

metrics:
  - z_500
  - t_850
  - u_850
  - v_850
  - 2t
  - msl

plot:
#not yet used
  - q_850
  - t_850
  - u_850
  - v_850
  - w_850 
  - z_850
  - msl
  - 2t

###################
#  OUTPUT BLOCK
###################
output:
  basedir: /ec/res4/scratch/syma/GNN-AE/ERA5/{resolution}/
  logging:
    log-dir: logs
    log-interval: 250
  checkpoints:
    # model checkpoints: used to resume training or do inference
    ckpt-dir: checkpoints
  model:
    save-top-k: 10
    checkpoint-filename: aifs-ae-1h-ckpt-{epoch:02d}-{val_ae_wmse:.3e}
  plots:
    plot-dir: plots

###################
#  GRAPH BLOCK
###################
graph:
  data-basedir: /ec/res4/hpcperm/nesl/gnn/
  data-file: graph_mappings_normed_edge_attrs1_fixed_weights_{resolution}_h_0_1_2_3_4_5.pt

###################
#  MODEL BLOCK
###################
model:
  debug:
    # this will detect and trace back NaNs / Infs etc. but will slow down training
    anomaly-detection: False
  wandb:
    enabled: True
  dataloader:
    num-workers:
      training: 8
      validation: 8
      test: 8
      predict: 8
    batch-size:
      training: 4
      validation: 4
      test: 4
      predict: 4

  # logger options (these probably come with some overhead)
  log-gradients: False
  log-parameters: False

  # resume training from a checkpoint
  warm-restart:
    enabled: False
    # path should be relative to the output:checkpoints:chkpt-dir, as defined above
    ckpt-path: 
  
  # miscellaneous
  precision: 16-mixed  # "16" with Lightning < 2.0

  # runs only N training batches [N = integer | null]
  # if null then we run through all the batches
  limit-batches:
    training: null
    validation: null
    test: 20
    predict: 20

  # parallel strategy
  # if running on a single device set to "null" [Lightning < 2] or "auto" [Lightning 2.0]
  strategy: auto

  # number of GPUs per node and number of nodes (for DDP)
  num-gpus: 4
  num-nodes: 1

  # training settings
  lead-time: 6
  max-epochs: 50
  learn-rate: 0.00025

  # gradient accumulation across K batches, K >= 1 (if K == 1 then no accumulation)
  # the effective batch size becomes num-devices * batch-size * k
  accum-grad-batches: 1

  # clipp gradients, 0 : don't clip, default algorithm: norm, alternative: value
  gradient-clip-val: 0.
  gradient-clip-algorithm: value

  # stochastic weight averaging
  # https://pytorch.org/blog/stochastic-weight-averaging-in-pytorch/
  swa:
    enabled: False
    lr: 1.e-4

  # activate the pytorch profiler (disable this in production)
  profile: False

  # specific GNN encoder settings
  encoder:
    mapper-num-layers: 2
    activation: SiLU
    num-out-channels: 512
    mlp-extra-layers: 0
    dropout: 0.
