defaults:
  - hardware: atos_slurm
  - data: zarr
  - dataloader: rollout
  - model: gnn
  - training: default
  - diagnostics: eval_rollout
  - override hydra/job_logging: none
  - override hydra/hydra_logging: none
  - _self_

hardware:
  files:
    graph: graph_mappings_normed_edge_attrs1_${data.resolution}_h_0_1_2_3_4.pt
    warm_start: aifs-by_epoch-epoch_085-train_kcrps_0.000e+00.ckpt
    # keep the checkpoint name in sync with the loss type
  checkpoint:
    every_n_epochs: aifs-by_epoch-epoch_{epoch:03d}-rollout_{rollout:.0f}-train_kcrps_{train_kcrps_epoch:.3e}
    every_n_train_steps: aifs-by_step-epoch_{epoch:03d}-step_{step:06d}-rollout_{rollout:.0f}
    every_n_minutes: aifs-by_time-epoch_{epoch:03d}-step_{step:06d}-rollout_{rollout:.0f}
  num_gpus_per_model: 1
  num_gpus_per_ensemble: 2

model:
  num_channels: 128

dataloader:
  batch_size:
    training: 4
    validation: 4
  limit_batches:
    training: 4000
    validation: null  # minimum 4 for evaluation to work

training:
  run_id: 210e95a1-6f4a-4481-9832-3cb4779387a0
  lr:
    rate: 0.425e-4
    iterations: 300000
    min: 1.5e-7
  rollout:
    start: 3
    epoch_increment: 1
    max: 12
  ensemble_size_per_device: 2
  loss: kcrps
  eda_initial_perturbations: False

diagnostics:
  eval:
    enabled: True
    rollout: 12
    frequency: 5
  plot:
    parameters:
      23: t_850
      36: u_850
      49: v_850
      72: z_500
  logging:
    interval: 50
