defaults:
  - hardware: atos_slurm
  - data: zarr
  - dataloader: rollout
  - model: gnn
  - training: default
  - diagnostics: eval_rollout
  - override hydra/job_logging: none
  - override hydra/hydra_logging: none
  - _self_

### This file is for local experimentation.
##  When you commit your changes, assign the new features and keywords
##  to the correct defaults.

hardware:
  group_size: 2
  files:
    graph: graph_mappings_normed_edge_attrs1_${data.resolution}_h_0_1_2_3_4.pt
    training:
      an: panguweather-${data.resolution}-1979-2015-6h.zarr
    warm_start: aifs-ckpt-epoch_013-rollout_1-train_kcrps_0.000e+00.ckpt
  paths:
    training:
      an: /lus/h2resw01/fws4/lb/project/ai-ml/panguweather-${data.resolution}

model:
  num_channels: 128

dataloader:
  batch_size:
    training: 4
    validation: 4
  limit_batches:
    training: 4000
    validation: null # no limit

training:
  run_id: 4a173317-2476-4b64-8473-f8e190051ccc
  max_epochs: 25
  rollout:
    epoch_increment: 1
    max: 12
  ensemble_size: 4
  loss: 'patched_energy'

diagnostics:
  eval:
    enabled: True
    rollout: 2
    frequency: 5
  plot:
    parameters:
      23: t_850
      36: u_850
      49: v_850
      72: z_500
  logging:
    interval: 50
