defaults:
  - hardware: leo_slurm
  - data: zarr
  - dataloader: rollout
  - model: gnn
  - training: default
  - diagnostics: eval_rollout
  - override hydra/job_logging: none
  - override hydra/hydra_logging: none
  - _self_

### This file is for local experimentation.
##  When you commit your changes, assign the new features and keywords
##  to the correct defaults.

hardware:
  group_size: 2
  files:
     warm_start: 4a173317-2476-4b64-8473-f8e190051ccc/aifs-ckpt-epoch_013-rollout_1-train_kcrps_0.000e+00.ckpt

model:
  num_channels: 128

dataloader:
  batch_size:
    training: 4
    validation: 4
  limit_batches:
    training: 4000
    validation: null # no limit

training:
  run_id: null
  max_epochs: 40
  rollout:
    epoch_increment: 1
    max: 12
  ensemble_size: 4
  loss: 'patched_energy'

diagnostics:
  eval:
    enabled: True
    rollout: 2
    frequency: 5
  plot:
    parameters:
      23: t_850
      36: u_850
      49: v_850
      72: z_500
  logging:
    interval: 50
