defaults:
  - hardware: leo_slurm
  - data: zarr
  - dataloader: default
  - model: gnn
  - training: default
  - diagnostics: eval_rollout
  - override hydra/job_logging: none
  - override hydra/hydra_logging: none
  - _self_

### This file is for local experimentation.
##  When you commit your changes, assign the new features and keywords
##  to the correct defaults.

hardware:
  files:
    graph: graph_mappings_normed_edge_attrs1_${data.resolution}_h_0_1_2_3_4_5.pt
    warm_start: aifs-ens-h5-512-epoch_013-train_kcrps_0.000e+00-v8.ckpt
  group_size: 4

model:
  num_channels: 512

dataloader:
  batch_size:
    training: 1
    validation: 1
  limit_batches:
    training: 4000
    validation: null

training:
  run_id: null
  fork_run_id: 07896b31-fad5-4ddc-95fe-db6e73c6a571
  max_epochs: 30

  rollout:
    start: 2
    epoch_increment: 1
    max: 8
  ensemble_size: 2

diagnostics:
  eval:
    enabled: True
    rollout: 8
    frequency: 5
  plot:
    parameters:
      23: t_850
      72: z_500
  logging:
    interval: 100
