defaults:
  - hardware: leo_slurm
  - data: zarr
  - dataloader: default
  - model: gnn
  - training: default
  - diagnostics: eval_rollout
  - override hydra/job_logging: none
  - override hydra/hydra_logging: none
  - _self_

### This file is for local experimentation.
##  When you commit your changes, assign the new features and keywords
##  to the correct defaults.

hardware:
  files:
    graph: graph_mappings_normed_edge_attrs1_${data.resolution}_h_0_1_2_3_4_5.pt
    checkpoint: aifs-ens-h5-512-epoch_{epoch:03d}-train_kcrps_{train_kcrps_epoch:.3e}
    warm_start: aifs-ens-h5-512-epoch_005-train_kcrps_2.394e+00.ckpt
  group_size: 4

model:
  num_channels: 512

dataloader:
  batch_size:
    training: 2
    validation: 1
  limit_batches:
    training: 5000
    validation: null

training:
  run_id: 07896b31-fad5-4ddc-95fe-db6e73c6a571
  fork_run_id: null
  max_epochs: 30
  rollout:
    start: 1
    epoch_increment: 0
    max: 1
  ensemble_size: 2
  lr:
    rate: 0.325e-4
    iterations: 100000
    min: 1.5e-7

diagnostics:
  eval:
    enabled: True
    rollout: 8
    frequency: 5
  plot:
    parameters:
      23: t_850
      36: u_850
      49: v_850
      72: z_500
  logging:
    interval: 150
