defaults:
  - hardware: leo_slurm
  - data: zarr
  - dataloader: default
  - model: gnn
  - training: default
  - diagnostics: eval_rollout
  - override hydra/job_logging: none
  - override hydra/hydra_logging: none
  - _self_

### This file is for local experimentation.
##  When you commit your changes, assign the new features and keywords
##  to the correct defaults.

hardware:
  files:
    graph: graph_mappings_normed_edge_attrs1_${data.resolution}_h_0_1_2_3_4.pt
    warm_start: aifs-ckpt-epoch_009-val_kcrps_2.556e+00.ckpt
  group_size: 4

model:
  num_channels: 256

dataloader:
  batch_size:
    training: 2
    validation: 1
  limit_batches:
    training: 200
    validation: 100

training:
  run_id: null
  fork_run_id: slfuwr124zb
  max_epochs: 4

  rollout:
    start: 1
    epoch_increment: 1
    max: 4
  ensemble_size: 2

diagnostics:
  eval:
    enabled: True
    rollout: 8
    frequency: 5
  plot:
    parameters:
      23: t_850
      72: z_500
  logging:
    interval: 100
