defaults:
  - hardware: leo_slurm
  - data: zarr
  - dataloader: default
  - model: gnn
  - training: default
  - diagnostics: eval_rollout
  - override hydra/job_logging: none
  - override hydra/hydra_logging: none
  - _self_

### This file is for local experimentation.
##  When you commit your changes, assign the new features and keywords
##  to the correct defaults.

hardware:
  paths:
    training: /lus/h2resw01/fws4/lb/project/ai-ml/panguweather-${data.resolution}
    validation: /lus/h2resw01/fws4/lb/project/ai-ml/panguweather-${data.resolution}
  files:
    training: panguweather-${data.resolution}-1979-2015-6h.zarr
    validation: panguweather-${data.resolution}-2016-2017-6h.zarr
    graph: graph_mappings_normed_edge_attrs1_${data.resolution}_h_0_1_2_3_4_5.pt
    checkpoint: aifs-ens-h5-512-rollout_{rollout:.0f}_epoch_{epoch:03d}-train_kcrps_{train_kcrps_epoch:.3e}
    warm_start: aifs-ens-h5-512-epoch_021-train_kcrps_2.435e+00.ckpt
  group_size: 4

model:
  num_channels: 512

dataloader:
  batch_size:
    training: 1
    validation: 1
  limit_batches:
    training: 4000
    validation: null

training:
  run_id: null
  fork_run_id: 1720475f-314f-4412-9f56-715f448451ac
  max_epochs: 50

  rollout:
    start: 2
    epoch_increment: 1
    max: 8
  ensemble_size: 2
  lr:
    rate: 0.125e-5
    iterations: 100000
    min: 1.5e-7
  loss_scaling:
    pl:
      q: 0.6
      t: 12
      u: 0.8
      v: 0.5
      w: 0.001
      z: 8

diagnostics:
  eval:
    enabled: True
    rollout: 8
    frequency: 5
  plot:
    parameters:
      23: t_850
      36: u_850
      49: v_850
      72: z_500
  logging:
    interval: 150
