defaults:
  - hardware: leo_slurm
  - data: zarr
  - dataloader: default
  - model: gnn
  - training: default
  - diagnostics: eval_rollout
  - override hydra/job_logging: none
  - override hydra/hydra_logging: none
  - _self_

### This file is for local experimentation.
##  When you commit your changes, assign the new features and keywords
##  to the correct defaults.

hardware:
  files:
    graph: patches_graph_mappings_normed_edge_attrs1_${data.resolution}_h_0_1_2_3_4.pt
    training: panguweather-${data.resolution}-1979-2015-6h.zarr
  paths:
    training: /lus/h2resw01/fws4/lb/project/ai-ml/panguweather-${data.resolution}
  group_size: 2

model:
  num_channels: 128

dataloader:
  batch_size:
    training: 4
    validation: 4
  limit_batches:
    training: 4000
    validation: null # no limit

training:
  run_id: null
  rollout:
    start: 1
    epoch_increment: 0
    max: 1
  ensemble_size: 4
  loss: 'patched_energy'

diagnostics:
  eval:
    enabled: True
    rollout: 2
    frequency: 5
  plot:
    parameters:
      23: t_850
      36: u_850
      49: v_850
      72: z_500
  logging:
    interval: 50
