defaults:
  - hardware: atos_slurm
  - data: zarr
  - dataloader: default
  - model: gnn
  - training: default
  - diagnostics: eval_rollout
  - override hydra/job_logging: none
  - override hydra/hydra_logging: none
  - _self_

### This file is for local experimentation.
##  When you commit your changes, assign the new features and keywords
##  to the correct defaults.

hardware:
  paths:
    training:
      an: /lus/h2resw01/fws4/lb/project/ai-ml/panguweather-${data.resolution}
    validation:
      an: /lus/h2resw01/fws4/lb/project/ai-ml/panguweather-${data.resolution}
  files:
    training:
      an: panguweather-${data.resolution}-1979-2015-6h.zarr
    validation:
      an: panguweather-${data.resolution}-2016-2017-6h.zarr
    graph: graph_mappings_normed_edge_attrs1_${data.resolution}_h_0_1_2_3_4_5.pt
    checkpoint: aifs-ens-h5-512-rollout{rollout:.0f}-epoch_{epoch:03d}-train_patched_energy_{train_kcrps_epoch:.3e}
    patches: patches_voronoi_o96.npy
  group_size: 4

model:
  num_channels: 512

dataloader:
  batch_size:
    training: 2
    validation: 1
  limit_batches:
    training: 5000
    validation: null

training:
  run_id: null
  eda_initial_perturbations: True
  max_epochs: 100
  rollout:
    start: 1
    epoch_increment: 0
    max: 1
  ensemble_size: 2
  lr:
    rate: 0.425e-4
    iterations: 300000
    min: 1.5e-7
  loss_scaling:
    pl:
      q: 0.6
      t: 10
      u: 0.8
      v: 0.5
      w: 0.001
      z: 8
  loss: 'patched_energy'

diagnostics:
  eval:
    enabled: True
    rollout: 8
    frequency: 5
  plot:
    parameters:
      23: t_850
      36: u_850
      49: v_850
      72: z_500
  logging:
    interval: 150
