defaults:
  - hardware: atos_slurm
  - data: zarr
  - dataloader: ensemble_eda
  - model: gnn
  - training: default
  - diagnostics: eval_rollout
  - override hydra/job_logging: none
  - override hydra/hydra_logging: none
  - _self_

hardware:
  files:
    graph: graph_mappings_normed_edge_attrs1_${data.resolution}_h_0_1_2_3_4.pt
    # keep the checkpoint name in sync with the loss type
  checkpoint:
    every_n_epochs: aifs-by_epoch-epoch_{epoch:03d}-rollout_{rollout:.0f}-train_kcrps_{train_kcrps_epoch:.3e}
    every_n_train_steps: aifs-by_step-epoch_{epoch:03d}-step_{step:06d}-rollout_{rollout:.0f}
    every_n_minutes: aifs-by_time-epoch_{epoch:03d}-step_{step:06d}-rollout_{rollout:.0f}
  num_gpus_per_model: 1
  num_gpus_per_ensemble: 2

model:
  num_channels: 128
  processor:
    num_noise_channels: 4

dataloader:
  batch_size:
    training: 4
    validation: 4
  limit_batches:
    training: 200
    validation: 50  # minimum 4 for evaluation to work

training:
  lr:
    rate: 0.425e-4
    iterations: 300000
    min: 1.5e-7
  rollout:
    start: 1
    epoch_increment: 0
    max: 1
  ensemble_size_per_device: 3
  loss: kcrps
  eda_initial_perturbations: False

diagnostics:
  eval:
    enabled: True
    rollout: 2
    frequency: 5
  plot:
    parameters:
      - t_850
      - u_850
      - v_850
      - z_500
  logging:
    interval: 50
