defaults:
  - hardware: atos
  - paths: atos
  - files: atos
  - data: zarr
  - dataloader: default
  - model: gnn
  - training: default
  - diagnostics: eval_rollout
  - _self_

### This file is for local experimentation. 
##  When you commit your changes, assign the new features and keywords
##  to the correct defaults.
# For example to change from default GPU count:
hardware:
  num_gpus: 2
  num_nodes: 1
files:
  graph: graph_mappings_normed_edge_attrs1_${data.resolution}_h_0_1_2_3_4.pt
model:
  num_channels: 128
  hidden:
    num_layers: 8
dataloader:
  limit_batches:
    training: 150
    validation: 150
training:
  max_epochs: 2
