defaults:
  - hardware: mlux_slurm
  - data: zarr
  - dataloader: default
  - model: gnn
  - training: default
  - diagnostics: eval_rollout
  - override hydra/job_logging: none
  - override hydra/hydra_logging: none
  - _self_

hardware:
  files:
    graph: graph_mappings_normed_edge_attrs1_${data.resolution}_h_0_1_2_3_4.pt
    # keep the checkpoint name in sync with the loss type
    checkpoint: aifs-ens-kcrps-ckpt-epoch_{epoch:03d}-rollout_{rollout:.0f}-train_kcrps_{train_kcrps_epoch:.3e}
  num_gpus_per_model: 1
  num_gpus_per_ensemble: 1

model:
  num_channels: 16
  processor:
    num_layers: 2
    num_noise_channels: 4
    # must have (num_channels + num_noise_channels) % num_heads == 0 !
    num_heads: 4
  trainable_parameters:
    era: 2
    hidden: 2
    era2hidden: 2
    hidden2era: 2
    hidden2hidden: 2

dataloader:
  num_workers:
    training: 1
    validation: 1
  batch_size:
    training: 1
    validation: 1
  limit_batches:
    training: 50
    validation: 50

training:
  max_epochs: 2
  rollout:
    start: 1
    epoch_increment: 0
    max: 1
  ensemble_size_per_device: 2
  loss: kcrps
  eda_initial_perturbations: False

diagnostics:
  log:
    wandb:
      offline: True
  eval:
    enabled: True
    rollout: 2
    frequency: 5
  plot:
    parameters:
      23: t_850
      36: u_850
      49: v_850
      72: z_500
  logging:
    interval: 10
