eval:
  enabled: False
  # use this to evaluate the model over longer rollouts, every so many validation batches
  rollout: 12
  frequency: 75
plot:
  enabled: True
  frequency: 750
  sample_idx: 0
  per_sample: 6
  parameters:
    10: q_850
    23: t_850
    36: u_850
    49: v_850
    75: z_850
    83: 2t
    81: 10u
    82: 10v
    79: msl
  learned_features: True

debug:
  # this will detect and trace back NaNs / Infs etc. but will slow down training
  anomaly_detection: False

# activate the pytorch profiler (disable this in production)
profiler: False

logging:
  wandb: True
  # logger options (these probably come with some overhead)
  gradients: False
  parameters: False
  interval: 100
