defaults:
  - paths: leo
  - files: leo

# parallel strategy
# if running on a single device set to "null" [Lightning < 2] or "auto" [Lightning 2.0]
strategy: auto
# number of GPUs per node and group, and number of nodes (for DDP)
num_gpus_per_node: 1
num_nodes: 1
group_size: 1
