training:
  an: panguweather-${data.resolution}-1979-2015-6h.zarr
  eda: aifs-ea-an-enda-0001-mars-${data.resolution}-1979-2015-6h-v1.zarr
validation:
  an: panguweather-${data.resolution}-2016-2017-6h.zarr
  eda: aifs-ea-an-enda-0001-mars-${data.resolution}-2016-2017-6h-v1.zarr
graph: graph_mappings_normed_edge_attrs1_${data.resolution}_h_0_1_2_3_4_5.pt
checkpoint:
  every_n_epochs: aifs-by_epoch-epoch_{epoch:03d}-train_kcrps_{train_kcrps_epoch:.3e}
  every_n_train_steps: aifs-by_step-epoch_{epoch:03d}-step_{step:06d}
  every_n_minutes: aifs-by_time-epoch_{epoch:03d}-step_{step:06d}
patches: patches_voronoi_${data.resolution}.npy
warm_start: null
