dataset: 1959-2022-6h-512x256_equiangular_conservative.zarr
graph: graph.pt
checkpoint:
  every_n_epochs: aifs-by_epoch-epoch_{epoch:03d}-val_wmse_{val_wmse:.3e}
  every_n_train_steps: aifs-by_step-epoch_{epoch:03d}
  every_n_minutes: aifs-by_time-epoch_{epoch:03d}-step_{step:06d}
warm_start: null
