training:
  an: panguweather-${data.resolution}-1979-2015-6h.zarr
  eda: aifs-ea-an-enda-0001-mars-${data.resolution}-1979-2015-6h-v1.zarr
validation:
  an: panguweather-${data.resolution}-2016-2017-6h.zarr
  eda: aifs-ea-an-enda-0001-mars-${data.resolution}-2016-2017-6h-v1.zarr
graph: graph_mappings_normed_edge_attrs1_${data.resolution}_h_0_1_2_3_4_5.pt
checkpoint: aifs-ens-kcrps-ckpt-epoch_{epoch:03d}-rollout_{rollout:.0f}-train_kcrps_{train_kcrps_epoch:.3e}
patches: patches_voronoi_${data.resolution}.npy
warm_start: null
