prefetch_factor: 2

num_workers:
  training: 8
  validation: 8
  test: 8
  predict: 8
batch_size:
  training: 2
  validation: 4
  test: 4
  predict: 4
# runs only N training batches [N = integer | null]
# if null then we run through all the batches
limit_batches:
  training: 400
  validation: 200
  test: 20
  predict: 20
