prefetch_factor: 2

num_workers:
  training: 1
  validation: 1
  test: 1
  predict: 1
batch_size:
  training: 2
  validation: 4
  test: 4
  predict: 4
# runs only N training batches [N = integer | null]
# if null then we run through all the batches
limit_batches:
  training: null
  validation: null
  test: 20
  predict: 20
