prefetch_factor: 2

num_workers:
  training: 8
  validation: 8
  test: 8
  predict: 8
batch_size:
  training: 2
  validation: 4
  test: 4
  predict: 4
# runs only N training batches [N = integer | null]
# if null then we run through all the batches
limit_batches:
  training: null
  validation: null
  test: 20
  predict: 20

# ============
# Dataloader definitions
# These follow the ecml-tools patterns
# You can make these as complicated for merging as you like
# See Readme: https://github.com/ecwmf-lab/ecml-tools/
# ============

training:
  dataset: ${hardware.paths.data}/${hardware.files.dataset}
  start: null
  end: 2020
  frequency: ${data.frequency}

validation:
  dataset: ${hardware.paths.data}/${hardware.files.dataset}
  start: 2021
  end: 2021
  frequency: ${data.frequency}

test:
  dataset: ${hardware.paths.data}/${hardware.files.dataset}
  start: 2022
  end: null
  frequency: ${data.frequency}
