prefetch_factor: 1

num_workers:
  training: 8
  validation: 8
  test: 8
  predict: 8
batch_size:
  training: 1
  validation: 1
  test: 4
  predict: 4
# runs only N training batches [N = integer | null]
# if null then we run through all the batches
limit_batches:
  training: null
  validation: null
  test: 20
  predict: 20
