# specific GNN encoder settings
activation: GELU
num_channels: 1024

mlp:
  extra_layers: 0

processor:
  type: GNN # GNN or Transformer
  num_layers: 16
  num_channels: 1024
  chunks: 2
  heads: 16
  mlp_hidden_ratio: 4
  window_size: 512
  dropout: 0.0

encoder:
  heads: 16
  mlp_hidden_ratio: 4
  dropout: 0.0

decoder:
  heads: 16
  mlp_hidden_ratio: 4
  dropout: 0.0

trainable_parameters:
  era: 8
  hidden: 8
  era2hidden: 8
  hidden2era: 8
  hidden2hidden: 8
