# specific GNN encoder settings
activation: SiLU
num_channels: 512

mlp:
  extra_layers: 1

encoder:
  nchunks: 8

decoder:
  nchunks: 8

processor:
  num_layers: 16
  chunks: 2

trainable_parameters:
  era: 8
  hidden: 8
  era2hidden: 8
  hidden2era: 8
  hidden2hidden: 8
