# specific GNN encoder settings
activation: SiLU
num_channels: 256

mlp:
  extra_layers: 0
  dropout: 0.

encoder:
  num_chunks: 1

decoder:
  num_chunks: 1

processor:
  num_layers: 16
  num_noise_channels: 4
  chunks: 2

# choose rate of dropout of edges
edge_dropout:
  h2h: 0

trainable_parameters:
  era: 8
  hidden: 8
  era2hidden: 8
  hidden2era: 8
  hidden2hidden: 8
