# specific GNN encoder settings
activation: SiLU
num_channels: 1024

mlp:
  extra_layers: 0

processor:
  num_layers: 16
  chunks: 2
  heads: 16
  mlp_hidden_ratio: 4

encoder:
  heads: 16
  mlp_hidden_ratio: 4

decoder:
  heads: 16
  mlp_hidden_ratio: 4

trainable_parameters:
  era: 8
  hidden: 8
  era2hidden: 8
  hidden2era: 8
  hidden2hidden: 8
